### ISSUE TITLE
`create_module_declaration` fails if module exports constants and functions

### ISSUE THREAD

**Issue by vnphanquang** [Rich-Harris/dts-buddy#26]
Sorry I know the project is marked as WIP, but it's too helpful for me to not use it.

Given this module

```javascript
export const EVENTS = {
  init: 'tocinit',
};

/**
 * @param {HTMLElement} node
 * @param {string} detail
 * @returns {string}
 */
export function dispatchInit(node, detail) {
  node.dispatchEvent(new CustomEvent(EVENTS.init, { detail }));
  return detail;
}

```

`dts-buddy` fails with the following error

```bash
file://.../dts-buddy-repro/node_modules/.pnpm/dts-buddy@0.1.7/node_modules/dts-buddy/src/create-module-declaration.js:275
                                                                const index = segments.findIndex((segment) => segment[0] >= loc.column);
                                                                                       ^

TypeError: Cannot read properties of undefined (reading 'findIndex')
    at file://.../dts-buddy-repro/node_modules/.pnpm/dts-buddy@0.1.7/node_modules/dts-buddy/src/create-module-declaration.js:275:32
    at visitNodes (.../dts-buddy-repro/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/typescript.js:27716:24)
    at forEachChildInSourceFile (.../dts-buddy-repro/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/typescript.js:28338:18)
    at Object.forEachChild (.../dts-buddy-repro/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/typescript.js:27801:37)
    at create_module_declaration (file://.../dts-buddy-repro/node_modules/.pnpm/dts-buddy@0.1.7/node_modules/dts-buddy/src/create-module-declaration.js:226:7)
    at createBundle (file://.../dts-buddy-repro/node_modules/.pnpm/dts-buddy@0.1.7/node_modules/dts-buddy/src/index.js:119:43)
    at file://.../dts-buddy-repro/scripts/generate-dts-bundle.js:3:7
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Minimal production can be found here: https://github.com/vnphanquang/dts-buddy-repro

Would love to help but I don't know much about the internal working here, very sorry 🙏🏼

**Comment by Rich-Harris** [comment]
thanks!
